In [38]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

from sklearn.neighbors import KNeighborsClassifier
from sklearn.cluster import KMeans
from sklearn.metrics import confusion_matrix
from sklearn.metrics import ConfusionMatrixDisplay
from sklearn.metrics import f1_score
from sklearn.metrics import accuracy_score
from sklearn.naive_bayes import GaussianNB
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.preprocessing import LabelEncoder
from sklearn import tree
import math
import os
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from icecream import ic
from sklearn.datasets import load_iris
import zipfile as zp
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans,DBSCAN
from scipy.cluster.hierarchy import linkage,dendrogram,cut_tree


In [29]:
data=pd.read_csv("D:/HALDEN/downloads/Mall_Customers.csv")
data.head(10)

CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
0           1    Male   19                  15                      39
1           2    Male   21                  15                      81
2           3  Female   20                  16                       6
3           4  Female   23                  16                      77
4           5  Female   31                  17                      40
5           6  Female   22                  17                      76
6           7  Female   35                  18                       6
7           8  Female   23                  18                      94
8           9    Male   64                  19                       3
9          10  Female   30                  19                      72

In [30]:
data['Gender']=data['Gender'].map({'Male':1,'Female':0})

In [31]:
from sklearn.cluster import KMeans  #Importing our clustering algorithm: KMeans
kmeans=KMeans(n_clusters=5, random_state=0)  #Cluster our data by choosing 5 as number of clusters
kmeans.fit(data)

C:\Users\HALDEN\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\cluster\_kmeans.py:1412: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  super()._check_params_vs_input(X, default_n_init=10)


KMeans(n_clusters=5, random_state=0)

In [32]:
labels=pd.DataFrame(kmeans.labels_)
labels

0
0    4
1    1
2    4
3    1
4    4
..  ..
195  0
196  2
197  0
198  2
199  0

[200 rows x 1 columns]

In [24]:
data['label']=labels

In [33]:
kmeans.predict(data)
print(kmeans.cluster_centers_)   #Printing the coordinates of cluster centers.
#Each inner list represents the coordinates of a cluster center.

[[162.           0.46153846  32.69230769  86.53846154  82.12820513]
 [ 26.28         0.4         26.04        27.6         76.84      ]
 [162.           0.52631579  40.39473684  87.          18.63157895]
 [ 89.47058824   0.44117647  43.91176471  56.58823529  50.04411765]
 [ 29.5          0.33333333  44.1         29.76666667  26.83333333]]


In [40]:
plt.scatter(data["Annual Income (k$)"][data.label_ == 0],          
            data["Spending Score (1-100)"][data.label_ == 0],s=80,c='magenta',label='Careful')
plt.scatter(data["Annual Income (k$)"][data.label_ == 1],
           data["Spending Score (1-100)"][data.label_ == 1],s=80,c='yellow',label='Standard')
plt.scatter(data["Annual Income (k$)"][data.label_ == 2],
           data["Spending Score (1-100)"][data.label_ == 2],s=80,c='green',label='Target')
plt.scatter(data["Annual Income (k$)"][data.label_ == 3], 
           data["Spending Score (1-100)"][data.label_ == 3],s=80,c='cyan',label='Careless')
plt.scatter(data["Annual Income (k$)"][data.label_ == 4], 
           data["Spending Score (1-100)"][data.label_ == 4],s=80,c='burlywood',label='Sensible')
plt.scatter(kmeans.cluster_centers_[:, 0], kmeans.cluster_centers_[:, 1], s=300, c='red', label = 'Centroids')
plt.title('Clusters of Customers')
plt.xlabel('Annual Income(k$)')
plt.ylabel('Spending Score(1-100')
plt.legend()
plt.show()


AttributeError: 'DataFrame' object has no attribute 'label_'

In [39]:
sum_of_squared_dist=[]
K=range(1,15)
for k in K:
    km=KMeans(n_clusters=k)
    km=km.fit(data)
    sum_of_squared_dist.append(km.inertia_)
    

C:\Users\HALDEN\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\cluster\_kmeans.py:1412: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  super()._check_params_vs_input(X, default_n_init=10)
C:\Users\HALDEN\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\cluster\_kmeans.py:1412: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  super()._check_params_vs_input(X, default_n_init=10)
C:\Users\HALDEN\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\cluster\_kmeans.py:1412: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. 